# Generated by Django 2.2.3 on 2021-05-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Yvp', models.CharField(max_length=80)),
                ('Ysp', models.CharField(max_length=80)),
                ('Ywp', models.CharField(max_length=80)),
                ('ifp', models.CharField(max_length=80)),
                ('ivp', models.CharField(max_length=80)),
                ('ilp', models.CharField(max_length=80)),
                ('fvp', models.CharField(max_length=80)),
                ('flp', models.CharField(max_length=80)),
                ('ffp', models.CharField(max_length=80)),
                ('fplp', models.CharField(max_length=80)),
                ('tfp', models.CharField(max_length=80)),
                ('tpl', models.CharField(max_length=80)),
                ('link', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('num', models.CharField(max_length=20)),
            ],
        ),
    ]
