# Generated by Django 2.2.3 on 2021-05-10 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Ysp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Yvp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Ywp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ffp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='flp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fplp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fvp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ifp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ilp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ivp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='num',
        ),
        migrations.RemoveField(
            model_name='user',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tfp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tpl',
        ),
    ]
