# Generated by Django 2.2.3 on 2021-05-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20210510_1301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
