# Generated by Django 2.2.3 on 2021-05-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firstapp', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=60)),
                ('quantity', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
